name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      url: ${{ steps.build.output.url }}

    steps:
    - uses: actions/checkout@v2

    - name: Run "build"
      id: build
      run: echo "::set-output name=url::https://example.com"
      
  test-output:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo ${{ needs.build.outputs.url }}
    
